---

- name: Pip installed version.
  command: >
    pip --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: no
  register: pip_installed_version

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
  when: pip_installed_version.rc != 0

- name: Ensure dependencies are installed.
  become: yes
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - python-dev
    state: present
    update_cache: yes
