---

- name: Pip installed version.
  command: >
    pip --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: no
  register: pip_installed_version

- debug:
    var: pip_installed_version

- name: Install pip
  shell: |
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python get-pip.py
    rm get-pip.py
  args:
    warn: no
  when: pip_installed_version.rc != 0

- name: Install required python modules globally
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - docker-compose
#    - docker-py

- name: Create Docker registry docroot.
  file:
    state: directory
    path: "{{ docker_registry_data_directory }}"
    # Ownership necessary for nginx?
    #   owner: www-data
    #   group: www-data
    mode: "0755"

- name: Run docker registry container
  docker_container:
    exposed_ports: "{{ docker_registry_expose_port }}"
    image: "registry:2"
    name: registry
    published_ports: "0.0.0.0:{{ docker_registry_expose_port }}:{{ docker_registry_expose_port }}"
    volumes:
      - "{{ docker_registry_data_directory }}:{{ docker_registry_data_directory }}"
    pull: no
    restart_policy: unless-stopped
    # "reloaded" does not appear to be idempotent
    state: started
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker_registry_data_directory }}"
      PYTHONPATH: "/home/path/.local/lib/python2.7/site-packages"
